{
    "_Type": "Action.Type.ODataService.DraftEnabled.Edit",
    "Target": {
        "Service": "/risks_mobile/Services/RiskManagementService.service",
        "EntitySet": "Mitigations",
        "ReadLink": "{@odata.readLink}"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": {
        "Name": "/risks_mobile/Actions/UpdateEntitySuccessMessage.action",
        "Properties": {
            "Message": "Draft Edit"
        }
    },
    "OnFailure": "/risks_mobile/Actions/UpdateEntityFailureMessage.action"
}