{
    "Target": {
        "EntitySet": "Mitigations",
        "Service": "/risks_mobile/Services/RiskManagementService.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/risks_mobile/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/risks_mobile/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}